### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by TristanCP** [resin-io-projects/resin-node-red#1]
Hi,

this  is nice to have a resin-node-red template to startup, but I think you could made it more explicit you have to setup env vars before you can do anyting in the Node-RED console, because it's not so obvious and you can actually see the interface and do some layout before you realize u can't save or run anything.

**Comment by curcuz** [comment]
hey @TristanCP can you tell me more about your issue? all the env vars have default fallback values so you shouldn't be required to set them if you are good with sticking with the defaults descrivbed in the readme ( [here](https://github.com/resin-io-projects/resin-node-red/blob/c9fb5a392b992d7cd0f7715256d7e374a0f4a835/app/settings.js#L23) is an example )

**Comment by curcuz** [comment]
@TristanCP just saw your PR. Makes sense, thanks for the contribution!

**Comment by TristanCP** [comment]
Adding a default fallback for USERNAME and PASSWORD would be a good idea for a quick start, but maybe not safe since the service is exposed on the internet from start.
